apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels: 
    name: mysql 
spec: 
  containers: 
    - image: mysql
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: my-secret-pw
        - name: MYSQL_DATABASE
          value: magento
      ports: 
        - containerPort: 3306
          name: db
