apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: magento-webapp-service
  name: magento-webapp-service
spec: 
  ports:
    - 
      targetPort: 80
      port: 80
  selector: 
    app: magento-webapp
  type: LoadBalancer
